// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqFnIx3V5pi3_ft-rGci50Jp0ZvFbkpXg',
    appId: '1:487359182520:web:6928f15a6daa9a17b9664d',
    messagingSenderId: '487359182520',
    projectId: 'demo2-15abe',
    authDomain: 'demo2-15abe.firebaseapp.com',
    storageBucket: 'demo2-15abe.appspot.com',
    measurementId: 'G-7Y1ZEMN7HW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQenCrxjB6pCiVbfVgwgnvdVlCoDQz5KM',
    appId: '1:487359182520:android:f19d8dbdcfbc39cbb9664d',
    messagingSenderId: '487359182520',
    projectId: 'demo2-15abe',
    storageBucket: 'demo2-15abe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBXBOxSswEEeYSgnHh69oAUtruKZq-TXI',
    appId: '1:487359182520:ios:7f9a59db03266b04b9664d',
    messagingSenderId: '487359182520',
    projectId: 'demo2-15abe',
    storageBucket: 'demo2-15abe.appspot.com',
    iosClientId: '487359182520-nlpd8eg4jth7pfharscqlnt8cbvm0m32.apps.googleusercontent.com',
    iosBundleId: 'com.example.demo2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBXBOxSswEEeYSgnHh69oAUtruKZq-TXI',
    appId: '1:487359182520:ios:7f9a59db03266b04b9664d',
    messagingSenderId: '487359182520',
    projectId: 'demo2-15abe',
    storageBucket: 'demo2-15abe.appspot.com',
    iosClientId: '487359182520-nlpd8eg4jth7pfharscqlnt8cbvm0m32.apps.googleusercontent.com',
    iosBundleId: 'com.example.demo2',
  );
}
